### PR TITLE
Update phase-space methods for offsets in FockBasis

### PR DESCRIPTION
**Pull request by david-pl**
To go along with https://github.com/qojulia/QuantumOpticsBase.jl/pull/14. The `wigner` function still needs to be updated, which could be tricky.

### CODE REVIEW

**Comment by Krastanov** [comment]
The test failures confuse me, as it just says `offset` is not present as a parameter. I assume it is actually an issue with the CI, not with the code.

However, running the tests locally did show a different problem for me:

```
phasespace: Error During Test at /home/stefan/Documents/ScratchSpace/quantumoptics/QuantumOptics/test/test_phasespace.jl:108
  Test threw exception
  Expression: isapprox(Wpsi_fock, wigner(psi_fock_off, X, Y), atol = 1.0e-5, rtol = 1.0e-5)
  BoundsError: attempt to access 98×98 Matrix{ComplexF64} at index [0, 97]
  Stacktrace:
   [1] getindex
     @ ./array.jl:802 [inlined]
   [2] _clenshaw_grid!(w::Matrix{ComplexF64}, L::Int64, ρ::Matrix{ComplexF64}, abs2_2α::Matrix{Float64}, _2α::Matrix{ComplexF64}, b0::Matrix{ComplexF64}, b1::Matrix{ComplexF64}, b2::Matrix{ComplexF64}, scale::Int64, N::Int64, offset::Int64)
     @ QuantumOptics ~/Documents/ScratchSpace/quantumoptics/QuantumOptics/src/phasespace.jl:183
   [3] wigner(rho::Operator{FockBasis{Int64}, FockBasis{Int64}, Matrix{ComplexF64}}, xvec::Vector{Float64}, yvec::Vector{Float64})
     @ QuantumOptics ~/Documents/ScratchSpace/quantumoptics/QuantumOptics/src/phasespace.jl:131
   [4] wigner(psi::Ket{FockBasis{Int64}, Vector{ComplexF64}}, x::Vector{Float64}, y::Vector{Float64})
     @ QuantumOptics ~/Documents/ScratchSpace/quantumoptics/QuantumOptics/src/phasespace.jl:140
   [5] macro expansion
     @ ~/Documents/ScratchSpace/quantumoptics/QuantumOptics/test/test_phasespace.jl:108 [inlined]
   [6] macro expansion
     @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1147 [inlined]
   [7] top-level scope
```

**Comment by Krastanov** [comment]
My last comment about problems with the tests seems to be wrong. I guess I am doing something incorrect when setting up the tests, because just copy-pasting the test in a julia console (running the git fockbasis-offset branch) runs fine. This all looks great to me, thank you for implementing it so incredibly quickly!

**Comment by david-pl** [comment]
The problem is that CI is using the latest release of QuantumOpticsBase, which does not have the offset implemented yet. I need to merge and release that first.
Cool, so you tried it locally? Did you do some testing on your use-case?

**Comment by david-pl** [comment]
> However, running the tests locally did show a different problem for me:

Yep, that was my bad. There was one occasion of out-of-bounds indexing, which I didn't notice at first because of `@inbounds`. Now things should be fine though.

**Comment by Krastanov** [comment]
Oh, I had not idea that Pkg.test overwrites inbounds and forces checks. (at least it did at some point https://discourse.julialang.org/t/package-test-failing-due-to-bounds-checking-enabled/2747 )

Yes, yesterday I use the code in this branch extensively to do some phase noise simulations. This worked great and I am really enjoying the library as a whole! Thank you!

**Comment by david-pl** [comment]
I was actually also not aware of that, but it just caught a bug that would have been merged otherwise. So yay for Pkg.test!

Great, good to know it works properly outside of tests as well.

**Pull request merged**
