### PR TITLE
DifferentialEquations v4

### PR DESCRIPTION
**Pull request by Datseris**
[x] master
[x] mcwf
[x] pumped
[x] schroedinger
[x] twolevel

### CODE REVIEW

**Comment by Datseris** [comment]
@david-pl what's up with the documentation string of `integrate` ?

```julia
"""
df(t, state::T, dstate::T)
"""
function integrate{T}(tspan::Vector{Float64}, df::Function, x0::Vector{Complex128},
            state::T, dstate::T, fout::Function;
            alg::OrdinaryDiffEq.OrdinaryDiffEqAlgorithm = OrdinaryDiffEq.DP5(),
            steady_state = false, tol = 1e-3, save_everystep = false,
            callback = nothing, kwargs...)

```
?...

**Comment by Datseris** [comment]
Hoorayyyyyy!!! all tests pass locally!

**Comment by david-pl** [comment]
You missed one line in semiclassical.master. All tests should pass now. Other than that, great work. Thanks!

**Comment by Datseris** [comment]
Good, thanks for the help! I had to admit it wasn't an easy process to find all lines, due to the huge amount of files!

**Comment by david-pl** [comment]
We could update to the new DiffEq syntax with much fewer changes by simply rewriting `df_` in `integrate`. This would keep the remaining syntax independent of DiffEqs syntax. Future syntax changes of DiffEq are then easier to handle. This is done in #197.

@Datseris Is there a specific reason for doing it this way?

**Pull request closed without merging**
