### PR TITLE
Change steady state sorting

### PR DESCRIPTION
**Pull request by david-pl**
@vtorggler is this okay now or are further changes required?

### CODE REVIEW

**Comment by vtorggler** [comment]
Maybe it would be better to sort it with respect to absolute value only. Then those eigenvalues with zero real and imaginary part are on top. But I guess it's ok as it is.

But, we also have to remove the normalization (division by trace(ops)) in liouvillianspectrum and add it in the eigenstate function.

**Comment by david-pl** [comment]
@vtorggler Good point. How about now?

**Comment by vtorggler** [comment]
Ok one last annoyance.

In Line 112 I would keep checking if the real part is 0, because I think if there are degeneracies it could be that there is an imaginary (oscillating) part. Rather warn earlier.

And the error message in Line 109 should be adapted. "No zero eigenvalue found." or so.

I should do this :)

**Comment by david-pl** [comment]
Ok then, how about now? ^^

**Comment by vtorggler** [comment]
Perfetto :+1:

**Pull request merged**
